curl -s -X POST $1 -d '
{
    "settings":{
        "index":{
            "analysis":{
                "analyzer":{
                    "city":{
                        "type":"custom",
                        "tokenizer":"standard",
                        "filter":[
                             "lowercase",
                             "asciifolding"
                        ]
                    },
                    "lowercase":{
                        "type":"custom",
                        "tokenizer":"standard",
                        "filter":[
                            "lowercase"
                        ]
                    }
                }
            }
        }
    }
}
'
